### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by artkpv** [mikemaccana/powershell-profile#1]
Hi, 
Thanks for sharing the profile! Find it useful to create mine.
Why not use `Invoke-Elevated` for `sudo`? 
The line: 
https://github.com/mikemaccana/powershell-profile/blob/0c5949130c874df32052ee4bbfaa8e9bafb13626/Microsoft.PowerShell_profile.ps1#L249

**Comment by mikemaccana** [comment]
Hey Artyom!

I'm not sure TBH! I got the sudo from https://github.com/
keithbloom/powershell-profile/blob/master/Microsoft.PowerShell_profile.ps1.
Any thoughts on how they compare?

Mike

**Comment by artkpv** [comment]
@mikemaccana 
The PSCX version looks more handy. It works with powershell script (like `sudo {echo abc}`) and with other apps (like `sudo notepad`). See `(get-command Invoke-Elevelated).Definition` for its code. And the version of @keithbloom works only with apps.

**Comment by mikemaccana** [comment]
Adjusted! Thanks for pointing this out @w1ld . Also pushed out a new release. 

How did you find this repo BTW?

**Comment by artkpv** [comment]
Great! 

I've searched for the most starred PS profile
